name: dockerize-log-server

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "services/log-server/**"
      - ".github/workflows/dockerize-log-server.yml"
      - "!**/*.md"
      - "!services/log-server/package-lock.json"

concurrency:
  group: dockerize-log-server-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dockerize-log-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/log-server
            docker.io/${{ secrets.DOCKER_USERNAME }}/log-server
          # https://github.com/docker/metadata-action#typesemver
          tags: |
            type=raw,value=latest,enable=true
            type=sha,enable=true,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Github Container Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./services/log-server
          file: ./services/log-server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64, linux/arm64

  trigger-workflow-build-cluster-image:
    needs: [dockerize-log-server]
    runs-on: ubuntu-latest
    steps:
      - name: trigger cluster image workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: docker_build_success
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "version": "latest"}'
